### ISSUE TITLE
Support Jira 7

### ISSUE THREAD

**Issue by marcar82** [maverick1982/jira-cards-printer#1]
Dear developer

this is marcar82 writing.
The "jira-cards-printer" does not work with Jira 7, is this a feature ?
If it is a bug,  it is unacceptable; please fix it and send me the patch as soon as possible.

best regards
Marco

**Comment by maverick1982** [comment]
Dear marcar82,

thanks for your highlighting.
This wasn't a feature and I have already fixed the issue.
You can download last development version or await the official release version.

Best regards,
Pasquale
